//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetSes2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresa
    {
        public string number { get; set; }
        public Nullable<double> prefix_code { get; set; }
        public string raion { get; set; }
        public string prefix { get; set; }
        public Nullable<double> house { get; set; }
    }
}
