//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetSes2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RayonSpb
    {
        public string Название_района { get; set; }
        public Nullable<double> Площадь { get; set; }
        public Nullable<double> Население { get; set; }
        public Nullable<double> Количество_станций_метро { get; set; }
        public string Тип_застройки { get; set; }
    }
}
