//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetSes2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public static Entities1 context;
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static Entities1 GetContext()
        {
            if (context == null)
            {
                context = new Entities1();
            }
            return context;
        }

        public virtual DbSet<Abonenti> Abonenti { get; set; }
        public virtual DbSet<AbonObor> AbonObor { get; set; }
        public virtual DbSet<Adresa> Adresa { get; set; }
        public virtual DbSet<InformDlyaSotrudnikov> InformDlyaSotrudnikov { get; set; }
        public virtual DbSet<Magistrali> Magistrali { get; set; }
        public virtual DbSet<RayonSpb> RayonSpb { get; set; }
        public virtual DbSet<SetDostupa> SetDostupa { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zayavki> Zayavki { get; set; }
    }
}
